---

language: ruby

cache:
  bundler: true
  directories:
    - "${HOME}/.npm"

install:
  - npm install

jobs:
  include:
    - stage: Prepare cache
      script: true
    - stage: Run tests
      script: npm test
