---

language: ruby

cache:
  directories:
    - "${HOME}/.bundle"
    #- "${HOME}/.gem"
    #- "${HOME}/.npm"
    #- "${HOME}/.nvm"
    #- "${HOME}/.rvm"

before_install:
  - npm install --global npm

install:
  - npm ci
  - bundle install

jobs:
  include:
    - stage: Run tests
      script:
        - npm test
        - python -m unittest tests.test_caesar
    - stage: Build and test webpage
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --disable-external
