---

language: node_js
node_js:
  - "node"

cache:
  - npm
  - bundle

install:
  - bundle install

jobs:
  include:
    - stage: Prepare cache
      script: true
    - stage: Run tests
      script: npm test
