---

language: ruby

cache:
  bundler: true
  directories:
    - "${HOME}/.npm"

before_install:
  - npm install --global npm

install:
  - npm ci
  - bundle install

jobs:
  include:
    - stage: Prepare cache
      script: true
    - stage: Run tests
      script: npm test
    - stage: Test webpage
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --disable-external
