---

language: python

cache:
  directories:
    - "${HOME}/.bundle"
    - "${HOME}/.gem"
    - "${HOME}/.npm"
    - "${HOME}/.rvm"
    - "${PWD}/node_modules"

before_install:
  - npm install --global npm
  - pip install tox

install:
  - npm ci
  - bundle install

jobs:
  include:
    - stage: Lint scripts
      python: 3.6
      script: tox -e pep8
    - stage: Test JavaScript scripts
      script:
        - # npm test
    - stage: Test Python scripts
      python: 2.7
      env: TOXENV=py27
      script:
        - # npm test
        - tox
    - stage: Test Python scripts
      python: 3.6
      env: TOXENV=py36
      script:
        - tox
    - stage: Build and test webpage
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --disable-external
