---

language: ruby

cache:
  bundler: true
  directories:
    - "${HOME}/.npm"

before_install:
  - npm install --global npm

install:
  - npm ci

jobs:
  include:
    - stage: Prepare cache
      script: true
    - stage: Run tests
      script: npm test
